CREATE VIEW TTCT_GV AS
SELECT GV.MaGV, GV.HoTen, GV.SDT, GV.GhiChu, 
DONVI.TenDonVi, COSO.TenCoSo 
FROM GV INNER JOIN DONVI ON DONVI.MaDonVi = GV.MaDonVi 
INNER JOIN COSO ON COSO.MaCoSo = DONVI.MaCoSO

SELECT * FROM TTCT_GV
